### ISSUE TITLE
Throws error when train.py is run on OSX

### ISSUE THREAD

**Issue by SebastianBoyd** [KaroAntonio/music-rnn-tensorflow#1]
Here is the full error log:
`W tensorflow/core/common_runtime/executor.cc:1027] 0x7f9b24e13e00 Compute status: Not found: save/model.ckpt.tempstate2130419365824857242
     [[Node: save/save = SaveSlices[T=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/save/tensor_names, save/save/shapes_and_slices, RNN/BasicLSTMCell/Linear/Bias, RNN/BasicLSTMCell/Linear/Bias/Adam, RNN/BasicLSTMCell/Linear/Bias/Adam_1, RNN/BasicLSTMCell/Linear/Matrix, RNN/BasicLSTMCell/Linear/Matrix/Adam, RNN/BasicLSTMCell/Linear/Matrix/Adam_1, Variable, Variable/Adam, Variable/Adam_1, Variable_1, Variable_1/Adam, Variable_1/Adam_1, Variable_2, Variable_2/Adam, Variable_2/Adam_1, Variable_3, Variable_3/Adam, Variable_3/Adam_1, beta1_power, beta2_power)]]
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    path = saver.save(sess, "save/model.ckpt")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 842, in save
    self._save_tensor_name, {self._filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.NotFoundError: save/model.ckpt.tempstate2130419365824857242
     [[Node: save/save = SaveSlices[T=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/save/tensor_names, save/save/shapes_and_slices, RNN/BasicLSTMCell/Linear/Bias, RNN/BasicLSTMCell/Linear/Bias/Adam, RNN/BasicLSTMCell/Linear/Bias/Adam_1, RNN/BasicLSTMCell/Linear/Matrix, RNN/BasicLSTMCell/Linear/Matrix/Adam, RNN/BasicLSTMCell/Linear/Matrix/Adam_1, Variable, Variable/Adam, Variable/Adam_1, Variable_1, Variable_1/Adam, Variable_1/Adam_1, Variable_2, Variable_2/Adam, Variable_2/Adam_1, Variable_3, Variable_3/Adam, Variable_3/Adam_1, beta1_power, beta2_power)]]
Caused by op u'save/save', defined at:
  File "train.py", line 28, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 406, in build
    save_tensor = self._AddSaveOps(filename_tensor, vars_to_save)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 108, in _AddSaveOps
    save = self.save_op(filename_tensor, vars_to_save)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 62, in save_op
    tensor_slices=[vs.slice_spec for vs in vars_to_save])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 145, in _save
    tensors, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 343, in _save_slices
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 640, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()`

**Comment by KaroAntonio** [comment]
not sure if this has to do with differences in tensorflow install? I also run on osx with no issue

**Comment by SebastianBoyd** [comment]
I'll try reinstalling later today

**Comment by SebastianBoyd** [comment]
My tensor flow installation was outdated
