### ISSUE TITLE
ImportError: This module is deprecated.  Use tf.nn.rnn_* instead.

### ISSUE THREAD

**Issue by oxmah** [KaroAntonio/music-rnn-tensorflow#2]
Hello !

I'm trying to use/test things with your code but I'm kinda stucked. When I start to train, I got this error and I didn't find a way through it : 

`Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from nn_utils.model import Model
  File "/media/workshop/DocumentsC1/Learning/music-rnn/nn_utils/model.py", line 2, in <module>
    from tensorflow.models.rnn import rnn, rnn_cell
  File "/home/workshop/miniconda2/lib/python2.7/site-packages/tensorflow/models/rnn/rnn.py", line 21, in <module>
    raise ImportError("This module is deprecated.  Use tf.nn.rnn_* instead.")
ImportError: This module is deprecated.  Use tf.nn.rnn_* instead.
`

If you could take a look, it'll be great !

Thanks !

**Comment by KaroAntonio** [comment]
Looks like you'll just have to adjust the import the import module as it suggests. Im not going to be able to look at it from my end for a while
